export const QUERY_KEY = {
  GET_USER_BY_USERID: 'GET_USER_BY_USERID',
  GET_ALL_ROOMS: 'GET_ALL_ROOMS',
  GET_ROOM_STATUS: 'GET_ROOM_STATUS',
  GET_ITEMS_BY_REALTIME: 'GET_ITEMS_BY_REALTIME',
};

export const MANAGER = 'alert';
