name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Create and activate virtual environment, install dependencies
      - name: Install dependencies
        run: |
          cd backend
          python3 -m venv pig
          source pig/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Build Docker image
      - name: Build Docker image
        run: |
          cd backend
          TAG=${{ github.sha }}
          docker build --no-cache -t pig:$TAG .

      # Stop and remove existing Docker container
      - name: Stop and Remove Existing Docker Container
        run: |
          TAG=${{ github.sha }}
          CONTAINER_ID=$(docker ps -q --filter ancestor=pig:$TAG)
          if [ -n "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          fi

      # Run Docker container
      - name: Deploy Docker container
        run: |
          TAG=${{ github.sha }}
          docker run -d -p 8000:8000 pig:$TAG
