name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code with latest updates
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Create and activate virtual environment, install dependencies
      - name: Install dependencies
        run: |
          echo ${{ secrets.TYPE }}
          cd backend
          python3 -m venv pig
          source pig/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Stop and remove any running container using the previous image
      - name: Stop and Remove Existing Docker Container
        run: |
          CONTAINER_ID=$(docker ps -q --filter ancestor=pig)
          if [ -n "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          fi

      # Remove Docker images except for the base images
      - name: Remove Application Docker Images
        run: |
          docker images --filter "dangling=true" -q | xargs -r docker rmi -f


      # Build Docker image
      - name: Build Docker image
        run: |
          cd backend
          TAG=${{ github.sha }}
          docker build --no-cache -t pig:$TAG .
          docker tag pig:$TAG pig:latest

      # Run Docker container
      - name: Deploy Docker container
        env:
          TYPE: ${{ secrets.TYPE }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AUTH_URI: ${{ secrets.AUTH_URI }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
          CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
          UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
        run: |
          docker run -d --name pig_app -p 8000:8000 pig:latest || exit 1
      
      # Wait for a few seconds to ensure the container has started
      - name: Wait for Container Startup
        run: sleep 5
      
      # Verify if the Docker container is running
      - name: Verify Container is Running
        run: |
          if [ -z "$(docker ps -q -f name=pig_app)" ]; then
            echo "Deployment failed: Container is not running."
            echo "Fetching logs..."
            docker logs pig_app || echo "No logs available: Container may have failed immediately."
            exit 1
          else
            echo "Deployment successful: Container is running."
          fi
