name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code with latest updates
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Create and activate virtual environment, install dependencies
      - name: Install dependencies
        run: |
          cd backend
          python3 -m venv pig
          source pig/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Stop and remove any running container using the previous image
      - name: Stop and Remove Existing Docker Container
        run: |
          CONTAINER_ID=$(docker ps -q --filter ancestor=pig)
          if [ -n "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          fi

      # Remove all existing Docker images
      - name: Remove All Docker Images
        run: |
          docker rmi -f $(docker images -q) || true

      # Build Docker image
      - name: Build Docker image
        run: |
          cd backend
          TAG=${{ github.sha }}
          docker build --no-cache -t pig:$TAG .
          docker tag pig:$TAG pig:latest

      # Run Docker container
      - name: Deploy Docker container
        run: |
          docker run -d -p 8000:8000 pig:latest
